#!/bin/bash

echo "server:XO"

# echo "Aronia: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AsamKumbang: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Blackberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Blackcurrant: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Blueberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Cloudberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Cranberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Crowberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Dewberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "FoxGrape: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Marionberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Raspberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Strawberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AmbrosiaMelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Cantaloupe: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "GaliaMelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "HoneydewMelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Watermelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Colonnade_Maypole_Apple: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Abiu: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Açaí: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Acerola: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Ackee: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AfricanBreadfruit: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AfricanCherryOrange: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AfricanCucumber: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AfricanMango: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Akebi: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AlexandriaStrawberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AlpineStrawberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AmanatsuOrange: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AmaouStrawberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Amara: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Ambarella: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AmbrosiaApple: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AmbrosiaMelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AmericanMayapple: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Amla: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Annatto: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Annona: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Apple: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Appleberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Apricot: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Aprium: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Araca-Boi: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AravaMelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Araza: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Aronia: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AsamKumbang: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "AsianPear: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Atemoya: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Avocado: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Babaco: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "BacuriFruit: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Bael: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "Banana: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Barbadine: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BarbadosCherry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Barberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Batuan: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BeachPlum: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Bearberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Bignay: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Bilberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Bilimbi: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Biriba: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BitterGourd: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BitterMelon: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BlackApple: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BlackCherry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BlackCurrant: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BlackMulberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BlackRaspberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BlackSapote: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Blackberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Blackcurrant: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BloodLime: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BloodOrange: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BluePassionfruit: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Blueberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BolivianMountainCoconut: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BottleGourd: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Boysenberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Bramble: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BrazilianGuava: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BreadFruit: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Breadfruit: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BrushCherry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BuddhaApple: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "BurdekinPlum: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "ButterFruit: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Cacao: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "CactusPear: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Calabash: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Calamansi: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Calamondin: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "CamuCamu: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Canistel: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "Cantaloupe: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
# echo "CapeGooseberry: Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, optio?"
echo "A::"

echo "Date: Wed, 01 Jan 2000 00:00:00 GMT"

echo "NomoreADK$:ad"

echo "Content-Type: text/html"
echo "aloha"

echo ""

echo "<!DOCTYPE html>"
echo "<html><head>"
echo "<title>CGI Script Say Hello</title>"
echo "<style>html {color-scheme: light dark;}</style>"
echo "</head><body>"
echo "<h1>Hello, I'm from Shell script!</h1>"
echo "</body></html>"