#!/usr/bin/python3

import time
print("run cgi-script hello", file=sys.stderr)

print("Content-Type: text/html")
time.sleep(2)
print("")

time.sleep(2)
print("<!DOCTYPE html>")
time.sleep(2)
print("<html><head>")
time.sleep(2)
print("<title>CGI Script Say Hello</title>")
time.sleep(2)
print("<style>html")
time.sleep(2)
print("{color-scheme: light dark;}")
time.sleep(2)
print("body { display: flex; justify-content: center; flex-direction: column ; align-items: center; height: 80vh; margin: 0;}")
time.sleep(2)
print("a { text-decoration: none; padding: 10px 20px; background-color: #303030; color: #808080; border-radius: 7px;}")
time.sleep(2)
print("a:hover {background-color: lightgrey; text-decoration: underline; }")
time.sleep(2)
print("</style>")
time.sleep(2)
print("</head><body>")
time.sleep(2)
print("<h1>Hello, I'm from Python script!</h1><br>")
time.sleep(2)
print("<a href=\"/cgi.html\">Go Back</a>")
time.sleep(2)
print("</body>\n</html>")

